# windowrule = float,class:^(kitty)$,title:^(kitty)$
windowrule {
    name=float-dev-dunno
    match:title = .*dunno.*
    float = true
}
windowrule {
    name = float-dev-rog
    match:title = .*Rog.*
    float = true
}
windowrule {
    name = float-dev-rog
    match:title = Diggity \(DEBUG\)
    float = true
}

